[workspace]
channels = ["conda-forge", "bioconda"]
name = "cell-calling"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
r-base = ">=4.4"
bioconductor-dropletutils = "*"
bioconductor-anndatar = "*"
r-optparse = "*"
